version: '3.7'

x-environment: &default-environment
  POSTGRES_USER: vscode
  POSTGRES_PASSWORD: notsecure
  POSTGRES_DB: wordpress-updates
  DATABASE_URL: postgres://vscode:notsecure@db:5432/wordpress-updates
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      <<: *default-environment
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      - ..:/workspace
    user: vscode
    command: sleep infinity
  db:
    image: 'postgres:14'
    restart: unless-stopped
    environment: *default-environment
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
